version: 2

updates:
  # Elixir dependencies
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    ignore:
      # Ignore major version updates for React (handle manually)
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    open-pull-requests-limit: 3
    target-branch: "main"
