# Codecov configuration
# TODO: Increase coverage targets as we add more tests
# Current low targets are temporary to allow CI to pass while building coverage

coverage:
  status:
    project:
      default:
        # Allow CI to pass with current coverage levels (head coverage: 2.28%)
        target: 2%
        threshold: 1%
    patch:
      default:
        # Don't fail on new code coverage (current patch: 5.01%)
        target: 4%
        threshold: 3%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false