import { Template } from '../types';

export const blogGenerationTemplate: Template = {
  id: 'blog-generation',
  name: 'SEO Blog Generation Pipeline',
  description: 'Automated blog content creation optimized for search engines',
  category: 'content-creation',
  nodes: [
    {
      id: 'topic-input',
      type: 'input',
      label: 'Content Topics',
      description: 'Target keywords, topics, and content goals',
      x: 100,
      y: 250,
    },
    {
      id: 'keyword-researcher',
      type: 'skill',
      label: 'Keyword Research',
      description: 'Research high-value keywords and search intent',
      x: 300,
      y: 200,
      config: {
        skill_type: 'seo_research',
        parameters: 'keyword_volume, competition_analysis, search_intent',
      },
    },
    {
      id: 'competitor-analyzer',
      type: 'skill',
      label: 'Competitor Analysis',
      description: 'Analyze top-ranking content for target keywords',
      x: 300,
      y: 300,
      config: {
        skill_type: 'content_analysis',
        parameters: 'serp_analysis, content_gaps, competitor_content',
      },
    },
    {
      id: 'content-strategist',
      type: 'agent',
      label: 'Content Strategist',
      description: 'Plan article structure and content strategy',
      x: 500,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.4,
        max_tokens: 800,
        system_prompt:
          'Create comprehensive content outlines that satisfy search intent and provide value to readers.',
      },
    },
    {
      id: 'research-assistant',
      type: 'agent',
      label: 'Research Assistant',
      description: 'Gather accurate information and statistics',
      x: 500,
      y: 350,
      config: {
        model: 'claude-3',
        temperature: 0.2,
        max_tokens: 700,
        system_prompt:
          'Research factual information, statistics, and expert insights for blog content.',
      },
    },
    {
      id: 'content-writer',
      type: 'agent',
      label: 'AI Content Writer',
      description: 'Write engaging, SEO-optimized blog content',
      x: 700,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.6,
        max_tokens: 2000,
        system_prompt:
          'Write high-quality, engaging blog posts that are optimized for SEO and provide value to readers.',
      },
    },
    {
      id: 'seo-optimizer',
      type: 'skill',
      label: 'SEO Optimization',
      description: 'Optimize content for search engine ranking',
      x: 700,
      y: 300,
      config: {
        skill_type: 'seo_optimization',
        parameters: 'meta_tags, headers, keyword_density, internal_links',
      },
    },
    {
      id: 'fact-checker',
      type: 'agent',
      label: 'Fact Checker',
      description: 'Verify accuracy of information and claims',
      x: 900,
      y: 150,
      config: {
        model: 'claude-3',
        temperature: 0.1,
        max_tokens: 600,
        system_prompt: 'Verify factual accuracy of content and flag any questionable claims.',
      },
    },
    {
      id: 'readability-checker',
      type: 'skill',
      label: 'Readability Analysis',
      description: 'Analyze and improve content readability',
      x: 900,
      y: 250,
      config: {
        skill_type: 'readability_analysis',
        parameters: 'flesch_kincaid, sentence_structure, paragraph_length',
      },
    },
    {
      id: 'image-suggester',
      type: 'skill',
      label: 'Visual Content Suggestions',
      description: 'Suggest relevant images, charts, and media',
      x: 900,
      y: 350,
      config: {
        skill_type: 'visual_content',
        parameters: 'stock_photos, chart_generation, infographic_suggestions',
      },
    },
    {
      id: 'quality-check',
      type: 'decision',
      label: 'Quality Standards Met?',
      description: 'Check if content meets quality and SEO standards',
      x: 1100,
      y: 250,
      config: {
        condition_type: 'rule_based',
        condition: 'quality_score > 8 AND seo_score > 85',
      },
    },
    {
      id: 'cms-publisher',
      type: 'skill',
      label: 'CMS Publishing',
      description: 'Publish content to website or blog platform',
      x: 1300,
      y: 200,
      config: {
        skill_type: 'cms_integration',
        parameters: 'wordpress, contentful, scheduling, meta_data',
      },
    },
    {
      id: 'seo-tracking',
      type: 'skill',
      label: 'SEO Performance Tracking',
      description: 'Monitor search rankings and organic traffic',
      x: 1300,
      y: 300,
      config: {
        skill_type: 'seo_monitoring',
        parameters: 'rank_tracking, traffic_analysis, google_analytics',
      },
    },
    {
      id: 'published-blog',
      type: 'output',
      label: 'Published SEO Blog',
      description: 'High-quality blog post optimized for search engines',
      x: 1500,
      y: 250,
    },
  ],
  connections: [
    {
      source: 'topic-input',
      target: 'keyword-researcher',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'topic-input',
      target: 'competitor-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'keyword-researcher',
      target: 'content-strategist',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'competitor-analyzer',
      target: 'research-assistant',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-strategist',
      target: 'content-writer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'research-assistant',
      target: 'content-writer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-writer',
      target: 'seo-optimizer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-writer',
      target: 'fact-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'seo-optimizer',
      target: 'readability-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fact-checker',
      target: 'readability-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'readability-checker',
      target: 'image-suggester',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'image-suggester',
      target: 'quality-check',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'quality-check',
      target: 'cms-publisher',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'quality-check',
      target: 'seo-tracking',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'cms-publisher',
      target: 'published-blog',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'seo-tracking',
      target: 'published-blog',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
