import { Template } from '../types';

export const customerSupportAutomationTemplate: Template = {
  id: 'customer-support-automation',
  name: 'Customer Support Automation',
  description: '24/7 AI-powered customer support with intelligent escalation',
  category: 'customer-service',
  nodes: [
    {
      id: 'customer-inquiry',
      type: 'input',
      label: 'Customer Inquiry',
      description: 'Support requests from chat, email, or phone',
      x: 100,
      y: 250,
    },
    {
      id: 'intent-classifier',
      type: 'skill',
      label: 'Intent Classification',
      description: 'Classify inquiry type and urgency level',
      x: 300,
      y: 200,
      config: {
        skill_type: 'nlp_classification',
        parameters: 'intent_categories: billing, technical, general, complaint',
      },
    },
    {
      id: 'sentiment-analyzer',
      type: 'skill',
      label: 'Sentiment Analysis',
      description: 'Analyze customer emotion and frustration level',
      x: 300,
      y: 300,
      config: {
        skill_type: 'sentiment_analysis',
        parameters: 'emotion_detection, urgency_scoring',
      },
    },
    {
      id: 'chatbot-agent',
      type: 'agent',
      label: 'Support Chatbot',
      description: 'AI agent to handle common support inquiries',
      x: 500,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.2,
        max_tokens: 700,
        system_prompt: 'Provide helpful customer support. Be empathetic and solution-focused.',
      },
    },
    {
      id: 'knowledge-memory',
      type: 'memory',
      label: 'Knowledge Base Memory',
      description: 'Store and retrieve customer interaction history',
      x: 500,
      y: 350,
      config: {
        storage_type: 'vector_database',
        retention_policy: 'permanent',
        embedding_model: 'sentence-transformers',
      },
    },
    {
      id: 'knowledge-search',
      type: 'skill',
      label: 'Knowledge Base Search',
      description: 'Search internal knowledge base for solutions',
      x: 700,
      y: 350,
      config: {
        skill_type: 'vector_search',
        parameters: 'knowledge_base, similarity_threshold: 0.8',
      },
    },
    {
      id: 'escalation-decision',
      type: 'decision',
      label: 'Requires Human?',
      description: 'Determine if human agent is needed',
      x: 700,
      y: 250,
      config: {
        condition_type: 'javascript',
        condition: 'needsHumanAgent(sentiment, complexity)',
      },
    },
    {
      id: 'human-agent',
      type: 'agent',
      label: 'Human Agent',
      description: 'Experienced support representative',
      x: 900,
      y: 150,
      config: {
        model: 'human',
        system_prompt: 'Handle complex customer issues with empathy and expertise.',
      },
    },
    {
      id: 'automated-resolution',
      type: 'skill',
      label: 'Automated Resolution',
      description: 'Resolve simple issues automatically',
      x: 900,
      y: 300,
      config: {
        skill_type: 'workflow_execution',
        parameters: 'resolution_workflows, auto_actions',
      },
    },
    {
      id: 'crm-api',
      type: 'api',
      label: 'CRM Integration',
      description: 'Update customer records and ticket status',
      x: 900,
      y: 400,
      config: {
        endpoint: '/api/crm/tickets',
        method: 'PUT',
        authentication: 'oauth2',
      },
    },
    {
      id: 'followup-loop',
      type: 'loop',
      label: 'Follow-up Loop',
      description: 'Automated follow-up until customer satisfaction',
      x: 1100,
      y: 400,
      config: {
        loop_type: 'for',
        iterations: 3,
        delay: '24_hours',
      },
    },
    {
      id: 'followup-scheduler',
      type: 'skill',
      label: 'Follow-up Scheduler',
      description: 'Schedule follow-up communications',
      x: 1300,
      y: 400,
      config: {
        skill_type: 'scheduling',
        parameters: 'followup_timing, satisfaction_check',
      },
    },
    {
      id: 'satisfaction-survey',
      type: 'skill',
      label: 'Satisfaction Survey',
      description: 'Send customer satisfaction survey',
      x: 1100,
      y: 250,
      config: {
        skill_type: 'survey_trigger',
        parameters: 'csat_survey, nps_scoring',
      },
    },
    {
      id: 'resolved-ticket',
      type: 'output',
      label: 'Resolved Support Ticket',
      description: 'Customer issue resolved and satisfaction measured',
      x: 1300,
      y: 250,
    },
  ],
  connections: [
    {
      source: 'customer-inquiry',
      target: 'intent-classifier',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'customer-inquiry',
      target: 'sentiment-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'intent-classifier',
      target: 'chatbot-agent',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'sentiment-analyzer',
      target: 'knowledge-memory',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'knowledge-memory',
      target: 'knowledge-search',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'chatbot-agent',
      target: 'escalation-decision',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'knowledge-search',
      target: 'escalation-decision',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'escalation-decision',
      target: 'human-agent',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'escalation-decision',
      target: 'automated-resolution',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'escalation-decision',
      target: 'crm-api',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'crm-api',
      target: 'followup-loop',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'followup-loop',
      target: 'followup-scheduler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'human-agent',
      target: 'satisfaction-survey',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'automated-resolution',
      target: 'satisfaction-survey',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'followup-scheduler',
      target: 'satisfaction-survey',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'satisfaction-survey',
      target: 'resolved-ticket',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
