import { Template } from '../types';

export const employeeOnboardingTemplate: Template = {
  id: 'employee-onboarding',
  name: 'Employee Onboarding Automation',
  description: 'Streamline new employee onboarding process with AI assistance',
  category: 'business-automation',
  nodes: [
    {
      id: 'new-hire-data',
      type: 'input',
      label: 'New Hire Information',
      description: 'Employee details from HR system',
      x: 100,
      y: 250,
    },
    {
      id: 'document-generator',
      type: 'skill',
      label: 'Document Generation',
      description: 'Generate personalized welcome packet and contracts',
      x: 300,
      y: 200,
      config: {
        skill_type: 'document_generation',
        parameters: 'welcome_packet, employment_contract, benefits_info',
      },
    },
    {
      id: 'account-provisioning',
      type: 'skill',
      label: 'Account Provisioning',
      description: 'Create email, system accounts, and access permissions',
      x: 300,
      y: 300,
      config: {
        skill_type: 'api_call',
        endpoint: '/accounts/provision',
        method: 'POST',
      },
    },
    {
      id: 'onboarding-assistant',
      type: 'agent',
      label: 'Onboarding Assistant',
      description: 'AI assistant to guide new employees through setup',
      x: 500,
      y: 250,
      config: {
        model: 'gpt-4',
        temperature: 0.3,
        max_tokens: 800,
        system_prompt:
          'Help new employees with onboarding questions and guide them through required steps.',
      },
    },
    {
      id: 'training-scheduler',
      type: 'skill',
      label: 'Training Scheduler',
      description: 'Schedule role-specific training sessions',
      x: 700,
      y: 150,
      config: {
        skill_type: 'calendar_integration',
        parameters: 'training_calendar, role_based_sessions',
      },
    },
    {
      id: 'equipment-request',
      type: 'skill',
      label: 'Equipment Request',
      description: 'Automatically order necessary equipment and supplies',
      x: 700,
      y: 250,
      config: {
        skill_type: 'api_call',
        endpoint: '/equipment/request',
        method: 'POST',
      },
    },
    {
      id: 'checklist-tracker',
      type: 'skill',
      label: 'Checklist Tracker',
      description: 'Track completion of onboarding tasks',
      x: 700,
      y: 350,
      config: {
        skill_type: 'task_tracking',
        parameters: 'onboarding_checklist, progress_monitoring',
      },
    },
    {
      id: 'completion-check',
      type: 'decision',
      label: 'All Tasks Complete?',
      description: 'Check if all onboarding tasks are finished',
      x: 900,
      y: 250,
      config: {
        condition_type: 'rule_based',
        condition: 'tasks_completed = 100% AND documents_signed = true AND training_passed = true',
      },
    },
    {
      id: 'welcome-survey',
      type: 'skill',
      label: 'Welcome Survey',
      description: 'Send feedback survey to new employee',
      x: 1100,
      y: 200,
      config: {
        skill_type: 'survey_trigger',
        parameters: 'welcome_survey, feedback_collection',
      },
    },
    {
      id: 'hr-notification',
      type: 'skill',
      label: 'HR Notification',
      description: 'Notify HR of completed onboarding',
      x: 1100,
      y: 300,
      config: {
        skill_type: 'notification',
        parameters: 'hr_team, completion_status',
      },
    },
    {
      id: 'onboarded-employee',
      type: 'output',
      label: 'Fully Onboarded Employee',
      description: 'Employee ready to start productive work',
      x: 1300,
      y: 250,
    },
  ],
  connections: [
    {
      source: 'new-hire-data',
      target: 'document-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'new-hire-data',
      target: 'account-provisioning',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'document-generator',
      target: 'onboarding-assistant',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'account-provisioning',
      target: 'onboarding-assistant',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'onboarding-assistant',
      target: 'training-scheduler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'onboarding-assistant',
      target: 'equipment-request',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'onboarding-assistant',
      target: 'checklist-tracker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'training-scheduler',
      target: 'completion-check',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'equipment-request',
      target: 'completion-check',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'checklist-tracker',
      target: 'completion-check',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'completion-check',
      target: 'welcome-survey',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'completion-check',
      target: 'hr-notification',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'welcome-survey',
      target: 'onboarded-employee',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'hr-notification',
      target: 'onboarded-employee',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
