import { Template } from '../types';

export const feedbackAnalysisTemplate: Template = {
  id: 'feedback-analysis',
  name: 'Customer Feedback Analysis',
  description: 'Analyze and act on customer feedback across all channels',
  category: 'customer-service',
  nodes: [
    {
      id: 'feedback-sources',
      type: 'input',
      label: 'Feedback Sources',
      description: 'Reviews, surveys, social media, and support tickets',
      x: 100,
      y: 250,
    },
    {
      id: 'text-preprocessor',
      type: 'skill',
      label: 'Text Preprocessing',
      description: 'Clean and normalize feedback text',
      x: 300,
      y: 200,
      config: {
        skill_type: 'text_processing',
        parameters: 'cleaning, normalization, language_detection',
      },
    },
    {
      id: 'feedback-categorizer',
      type: 'skill',
      label: 'Feedback Categorization',
      description: 'Categorize feedback by product, feature, or department',
      x: 300,
      y: 300,
      config: {
        skill_type: 'classification',
        parameters: 'categories: product, service, billing, shipping, quality',
      },
    },
    {
      id: 'sentiment-engine',
      type: 'agent',
      label: 'Sentiment Analysis Engine',
      description: 'Advanced sentiment analysis with emotion detection',
      x: 500,
      y: 200,
      config: {
        model: 'claude-3',
        temperature: 0.1,
        max_tokens: 600,
        system_prompt:
          'Analyze sentiment and emotions in customer feedback. Identify key concerns and positive aspects.',
      },
    },
    {
      id: 'trend-detector',
      type: 'skill',
      label: 'Trend Detection',
      description: 'Identify emerging patterns and trends',
      x: 500,
      y: 350,
      config: {
        skill_type: 'pattern_analysis',
        parameters: 'time_series_analysis, trend_identification',
      },
    },
    {
      id: 'priority-scorer',
      type: 'decision',
      label: 'High Priority Issue?',
      description: 'Score feedback priority based on impact and frequency',
      x: 700,
      y: 275,
      config: {
        condition_type: 'javascript',
        condition: 'calculatePriorityScore(feedback, trends)',
      },
    },
    {
      id: 'insight-generator',
      type: 'agent',
      label: 'Insight Generator',
      description: 'Generate actionable insights from feedback analysis',
      x: 900,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.3,
        max_tokens: 800,
        system_prompt: 'Generate actionable business insights from customer feedback data.',
      },
    },
    {
      id: 'alert-system',
      type: 'skill',
      label: 'Alert System',
      description: 'Send alerts for urgent issues or negative trends',
      x: 900,
      y: 350,
      config: {
        skill_type: 'notification',
        parameters: 'urgent_alerts, stakeholder_notifications',
      },
    },
    {
      id: 'report-generator',
      type: 'skill',
      label: 'Report Generation',
      description: 'Create comprehensive feedback analysis reports',
      x: 1100,
      y: 200,
      config: {
        skill_type: 'report_generation',
        parameters: 'executive_summary, detailed_analysis, charts',
      },
    },
    {
      id: 'action-recommender',
      type: 'skill',
      label: 'Action Recommendations',
      description: 'Recommend specific actions based on feedback',
      x: 1100,
      y: 300,
      config: {
        skill_type: 'recommendation_engine',
        parameters: 'action_suggestions, priority_ranking',
      },
    },
    {
      id: 'feedback-insights',
      type: 'output',
      label: 'Actionable Feedback Insights',
      description: 'Processed feedback with insights and recommendations',
      x: 1300,
      y: 250,
    },
  ],
  connections: [
    {
      source: 'feedback-sources',
      target: 'text-preprocessor',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'feedback-sources',
      target: 'feedback-categorizer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'text-preprocessor',
      target: 'sentiment-engine',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'feedback-categorizer',
      target: 'trend-detector',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'sentiment-engine',
      target: 'priority-scorer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'trend-detector',
      target: 'priority-scorer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'priority-scorer',
      target: 'insight-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'priority-scorer',
      target: 'alert-system',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'insight-generator',
      target: 'report-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'alert-system',
      target: 'action-recommender',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'report-generator',
      target: 'feedback-insights',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'action-recommender',
      target: 'feedback-insights',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
