import { Template } from '../types';

export const financialReportingTemplate: Template = {
  id: 'financial-reporting',
  name: 'Automated Financial Reporting',
  description: 'Generate financial reports with AI insights',
  category: 'data-analysis',
  nodes: [
    {
      id: 'financial-data',
      type: 'input',
      label: 'Financial Data Sources',
      description: 'ERP systems, bank feeds, and accounting software',
      x: 100,
      y: 250,
    },
    {
      id: 'data-validator',
      type: 'skill',
      label: 'Data Validation',
      description: 'Validate and clean financial data for accuracy',
      x: 300,
      y: 200,
      config: {
        skill_type: 'data_validation',
        parameters: 'reconciliation, duplicate_detection, outlier_analysis',
      },
    },
    {
      id: 'data-consolidator',
      type: 'skill',
      label: 'Data Consolidation',
      description: 'Consolidate data from multiple sources and formats',
      x: 300,
      y: 300,
      config: {
        skill_type: 'data_integration',
        parameters: 'multi_source_merge, currency_conversion, normalization',
      },
    },
    {
      id: 'financial-analyst',
      type: 'agent',
      label: 'Financial Analyst AI',
      description: 'Analyze financial metrics and performance indicators',
      x: 500,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.2,
        max_tokens: 1000,
        system_prompt:
          'Analyze financial data and provide insights on performance, trends, and key metrics.',
      },
    },
    {
      id: 'variance-analyzer',
      type: 'skill',
      label: 'Variance Analysis',
      description: 'Compare actuals vs budget and identify variances',
      x: 500,
      y: 350,
      config: {
        skill_type: 'variance_analysis',
        parameters: 'budget_comparison, forecast_accuracy, variance_thresholds',
      },
    },
    {
      id: 'kpi-calculator',
      type: 'skill',
      label: 'KPI Calculator',
      description: 'Calculate financial ratios and key performance indicators',
      x: 700,
      y: 150,
      config: {
        skill_type: 'financial_calculations',
        parameters: 'ratios, margins, liquidity, profitability, efficiency',
      },
    },
    {
      id: 'trend-analyzer',
      type: 'skill',
      label: 'Trend Analysis',
      description: 'Identify financial trends and patterns over time',
      x: 700,
      y: 250,
      config: {
        skill_type: 'time_series_analysis',
        parameters: 'seasonal_patterns, growth_rates, cyclical_trends',
      },
    },
    {
      id: 'benchmark-comparison',
      type: 'skill',
      label: 'Benchmark Comparison',
      description: 'Compare performance against industry benchmarks',
      x: 700,
      y: 350,
      config: {
        skill_type: 'benchmarking',
        parameters: 'industry_standards, peer_comparison, market_data',
      },
    },
    {
      id: 'insight-generator',
      type: 'agent',
      label: 'Insight Generator',
      description: 'Generate strategic insights and recommendations',
      x: 900,
      y: 200,
      config: {
        model: 'claude-3',
        temperature: 0.3,
        max_tokens: 800,
        system_prompt:
          'Generate strategic financial insights and actionable recommendations based on analysis.',
      },
    },
    {
      id: 'risk-assessor',
      type: 'skill',
      label: 'Risk Assessment',
      description: 'Identify financial risks and potential issues',
      x: 900,
      y: 350,
      config: {
        skill_type: 'risk_analysis',
        parameters: 'credit_risk, liquidity_risk, operational_risk',
      },
    },
    {
      id: 'report-builder',
      type: 'skill',
      label: 'Report Builder',
      description: 'Generate formatted financial reports and dashboards',
      x: 1100,
      y: 200,
      config: {
        skill_type: 'report_generation',
        parameters: 'executive_summary, detailed_financials, charts, tables',
      },
    },
    {
      id: 'forecast-model',
      type: 'skill',
      label: 'Financial Forecasting',
      description: 'Create financial forecasts and projections',
      x: 1100,
      y: 350,
      config: {
        skill_type: 'forecasting',
        parameters: 'revenue_projection, cash_flow, scenario_modeling',
      },
    },
    {
      id: 'financial-report',
      type: 'output',
      label: 'Financial Report',
      description: 'Complete financial analysis with insights and forecasts',
      x: 1300,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'financial-data',
      target: 'data-validator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'financial-data',
      target: 'data-consolidator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'data-validator',
      target: 'financial-analyst',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'data-consolidator',
      target: 'variance-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'financial-analyst',
      target: 'kpi-calculator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'financial-analyst',
      target: 'trend-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'variance-analyzer',
      target: 'benchmark-comparison',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'kpi-calculator',
      target: 'insight-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'trend-analyzer',
      target: 'insight-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'benchmark-comparison',
      target: 'risk-assessor',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'insight-generator',
      target: 'report-builder',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'risk-assessor',
      target: 'forecast-model',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'report-builder',
      target: 'financial-report',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'forecast-model',
      target: 'financial-report',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
