import { Template } from '../types';

export const fraudDetectionTemplate: Template = {
  id: 'fraud-detection',
  name: 'Real-time Fraud Detection',
  description: 'AI-powered fraud detection and prevention system',
  category: 'finance',
  nodes: [
    {
      id: 'transaction-stream',
      type: 'input',
      label: 'Transaction Stream',
      description: 'Real-time financial transactions from payment systems',
      x: 100,
      y: 250,
    },
    {
      id: 'transaction-parser',
      type: 'skill',
      label: 'Transaction Parser',
      description: 'Parse and normalize transaction data',
      x: 300,
      y: 200,
      config: {
        skill_type: 'data_parsing',
        parameters: 'amount, merchant, location, timestamp, payment_method',
      },
    },
    {
      id: 'user-profiler',
      type: 'skill',
      label: 'User Profile Lookup',
      description: 'Retrieve user spending patterns and history',
      x: 300,
      y: 300,
      config: {
        skill_type: 'profile_lookup',
        parameters: 'spending_history, behavioral_patterns, risk_profile',
      },
    },
    {
      id: 'fraud-analyst-ai',
      type: 'agent',
      label: 'Fraud Analyst AI',
      description: 'AI trained on fraud patterns and detection methods',
      x: 500,
      y: 200,
      config: {
        model: 'fraud-detection-llm',
        temperature: 0.1,
        max_tokens: 700,
        system_prompt:
          'Analyze transactions for fraudulent patterns using advanced detection techniques.',
      },
    },
    {
      id: 'anomaly-detector',
      type: 'skill',
      label: 'Anomaly Detection',
      description: 'ML-based anomaly detection for unusual patterns',
      x: 500,
      y: 350,
      config: {
        skill_type: 'ml_anomaly_detection',
        parameters: 'isolation_forest, autoencoder, statistical_outliers',
      },
    },
    {
      id: 'risk-calculator',
      type: 'skill',
      label: 'Risk Score Calculator',
      description: 'Calculate fraud risk score',
      x: 700,
      y: 200,
      config: {
        skill_type: 'risk_scoring',
        parameters: 'behavioral_score, location_risk, device_risk, velocity_checks',
      },
    },
    {
      id: 'geolocation-checker',
      type: 'skill',
      label: 'Geolocation Verification',
      description: 'Verify transaction location against user patterns',
      x: 700,
      y: 300,
      config: {
        skill_type: 'geo_verification',
        parameters: 'location_history, travel_patterns, impossible_travel_detection',
      },
    },
    {
      id: 'fraud-decision',
      type: 'decision',
      label: 'Fraud Risk Level?',
      description: 'Determine fraud risk level and required action',
      x: 900,
      y: 250,
      config: {
        condition_type: 'rule_based',
        condition: 'risk_score > 0.7 OR anomaly_score > 0.8 OR geo_risk = true',
      },
    },
    {
      id: 'auto-approve',
      type: 'skill',
      label: 'Auto Approve',
      description: 'Automatically approve low-risk transactions',
      x: 1100,
      y: 150,
      config: {
        skill_type: 'transaction_approval',
        parameters: 'auto_approve, low_risk_threshold, instant_processing',
      },
    },
    {
      id: 'manual-review',
      type: 'skill',
      label: 'Manual Review Queue',
      description: 'Queue medium-risk transactions for human review',
      x: 1100,
      y: 250,
      config: {
        skill_type: 'review_queue',
        parameters: 'manual_review, analyst_assignment, priority_scoring',
      },
    },
    {
      id: 'auto-block',
      type: 'skill',
      label: 'Auto Block',
      description: 'Automatically block high-risk transactions',
      x: 1100,
      y: 350,
      config: {
        skill_type: 'transaction_blocking',
        parameters: 'auto_block, high_risk_threshold, immediate_decline',
      },
    },
    {
      id: 'customer-notification',
      type: 'skill',
      label: 'Customer Notification',
      description: 'Notify customer of blocked transaction or verification needed',
      x: 1300,
      y: 200,
      config: {
        skill_type: 'customer_communication',
        parameters: 'sms_alert, email_notification, app_push, verification_request',
      },
    },
    {
      id: 'fraud-reporting',
      type: 'skill',
      label: 'Fraud Reporting',
      description: 'Generate fraud reports and update models',
      x: 1300,
      y: 350,
      config: {
        skill_type: 'reporting',
        parameters: 'fraud_analytics, model_feedback, compliance_reporting',
      },
    },
    {
      id: 'processed-transaction',
      type: 'output',
      label: 'Processed Transaction',
      description: 'Transaction approved, reviewed, or blocked based on fraud risk',
      x: 1500,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'transaction-stream',
      target: 'transaction-parser',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'transaction-stream',
      target: 'user-profiler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'transaction-parser',
      target: 'fraud-analyst-ai',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'user-profiler',
      target: 'anomaly-detector',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fraud-analyst-ai',
      target: 'risk-calculator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'anomaly-detector',
      target: 'geolocation-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'risk-calculator',
      target: 'fraud-decision',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'geolocation-checker',
      target: 'fraud-decision',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fraud-decision',
      target: 'auto-approve',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fraud-decision',
      target: 'manual-review',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fraud-decision',
      target: 'auto-block',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'auto-approve',
      target: 'processed-transaction',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'manual-review',
      target: 'customer-notification',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'auto-block',
      target: 'fraud-reporting',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'customer-notification',
      target: 'processed-transaction',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'fraud-reporting',
      target: 'processed-transaction',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
