import { Template } from '../types';

export const hrRecruitmentTemplate: Template = {
  id: 'hr-recruitment',
  name: 'AI-Powered Recruitment Pipeline',
  description: 'Streamline recruitment process with AI-driven candidate screening',
  category: 'business-automation',
  nodes: [
    {
      id: 'job-posting',
      type: 'input',
      label: 'Job Requirements',
      description: 'Job description, requirements, and candidate criteria',
      x: 100,
      y: 250,
    },
    {
      id: 'resume-parser',
      type: 'skill',
      label: 'Resume Parser',
      description: 'Extract and structure information from resumes',
      x: 300,
      y: 200,
      config: {
        skill_type: 'document_parsing',
        parameters: 'skills_extraction, experience_parsing, education_details, contact_info',
      },
    },
    {
      id: 'candidate-sourcer',
      type: 'skill',
      label: 'Candidate Sourcing',
      description: 'Source candidates from job boards and social networks',
      x: 300,
      y: 300,
      config: {
        skill_type: 'candidate_sourcing',
        parameters: 'linkedin_search, job_board_scraping, talent_databases',
      },
    },
    {
      id: 'recruiter-ai',
      type: 'agent',
      label: 'AI Recruiter',
      description: 'AI agent trained in recruitment best practices',
      x: 500,
      y: 200,
      config: {
        model: 'recruitment-gpt',
        temperature: 0.3,
        max_tokens: 800,
        system_prompt: 'Screen candidates based on job requirements and identify the best matches.',
      },
    },
    {
      id: 'skill-matcher',
      type: 'skill',
      label: 'Skill Matching',
      description: 'Match candidate skills against job requirements',
      x: 500,
      y: 350,
      config: {
        skill_type: 'skill_matching',
        parameters: 'technical_skills, soft_skills, experience_level, domain_expertise',
      },
    },
    {
      id: 'bias-checker',
      type: 'skill',
      label: 'Bias Detection',
      description: 'Check for unconscious bias in screening process',
      x: 700,
      y: 150,
      config: {
        skill_type: 'bias_detection',
        parameters: 'demographic_bias, name_bias, school_bias, fair_evaluation',
      },
    },
    {
      id: 'candidate-ranker',
      type: 'skill',
      label: 'Candidate Ranking',
      description: 'Rank candidates by fit score and qualifications',
      x: 700,
      y: 250,
      config: {
        skill_type: 'candidate_ranking',
        parameters: 'fit_score, experience_weight, skills_match, cultural_fit',
      },
    },
    {
      id: 'screening-questions',
      type: 'skill',
      label: 'Screening Questions',
      description: 'Generate personalized screening questions',
      x: 700,
      y: 350,
      config: {
        skill_type: 'question_generation',
        parameters: 'role_specific_questions, behavioral_questions, technical_assessment',
      },
    },
    {
      id: 'interview-scheduler',
      type: 'skill',
      label: 'Interview Scheduler',
      description: 'Automatically schedule interviews with top candidates',
      x: 900,
      y: 200,
      config: {
        skill_type: 'scheduling',
        parameters: 'calendar_integration, interviewer_availability, candidate_preferences',
      },
    },
    {
      id: 'rejection-automation',
      type: 'skill',
      label: 'Rejection Automation',
      description: 'Send personalized rejection emails to unsuitable candidates',
      x: 900,
      y: 350,
      config: {
        skill_type: 'email_automation',
        parameters: 'personalized_feedback, professional_tone, future_opportunities',
      },
    },
    {
      id: 'candidate-communication',
      type: 'agent',
      label: 'Candidate Communication',
      description: 'Handle candidate inquiries and provide updates',
      x: 1100,
      y: 200,
      config: {
        model: 'communication-gpt',
        temperature: 0.4,
        max_tokens: 600,
        system_prompt: 'Communicate professionally with candidates and provide helpful updates.',
      },
    },
    {
      id: 'recruitment-analytics',
      type: 'skill',
      label: 'Recruitment Analytics',
      description: 'Track recruitment metrics and optimize process',
      x: 1100,
      y: 350,
      config: {
        skill_type: 'analytics',
        parameters: 'time_to_hire, cost_per_hire, source_effectiveness, conversion_rates',
      },
    },
    {
      id: 'qualified-candidates',
      type: 'output',
      label: 'Qualified Candidates',
      description: 'Screened and ranked candidates ready for interview',
      x: 1300,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'job-posting',
      target: 'resume-parser',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'job-posting',
      target: 'candidate-sourcer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'resume-parser',
      target: 'recruiter-ai',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'candidate-sourcer',
      target: 'skill-matcher',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recruiter-ai',
      target: 'bias-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recruiter-ai',
      target: 'candidate-ranker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'skill-matcher',
      target: 'screening-questions',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'bias-checker',
      target: 'interview-scheduler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'candidate-ranker',
      target: 'interview-scheduler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'screening-questions',
      target: 'rejection-automation',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'interview-scheduler',
      target: 'candidate-communication',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'rejection-automation',
      target: 'recruitment-analytics',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'candidate-communication',
      target: 'qualified-candidates',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recruitment-analytics',
      target: 'qualified-candidates',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
