import { Template } from '../types';

export const invoiceProcessingTemplate: Template = {
  id: 'invoice-processing',
  name: 'Invoice Processing Automation',
  description: 'Automate invoice processing from receipt to payment approval',
  category: 'business-automation',
  nodes: [
    {
      id: 'invoice-input',
      type: 'input',
      label: 'Invoice Documents',
      description: 'Receive invoices via email, upload, or API',
      x: 100,
      y: 200,
    },
    {
      id: 'ocr-extraction',
      type: 'skill',
      label: 'OCR Data Extraction',
      description: 'Extract text and data from invoice images/PDFs',
      x: 300,
      y: 200,
      config: {
        skill_type: 'ocr',
        parameters: 'invoice_fields: vendor, amount, date, line_items',
      },
    },
    {
      id: 'data-validator',
      type: 'agent',
      label: 'Data Validator',
      description: 'AI agent to validate extracted invoice data',
      x: 500,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.1,
        max_tokens: 500,
        system_prompt: 'Validate invoice data for accuracy and completeness. Flag discrepancies.',
      },
    },
    {
      id: 'vendor-lookup',
      type: 'skill',
      label: 'Vendor Verification',
      description: 'Verify vendor against approved suppliers database',
      x: 700,
      y: 150,
      config: {
        skill_type: 'database_lookup',
        parameters: 'vendor_database, tax_id_verification',
      },
    },
    {
      id: 'amount-validation',
      type: 'decision',
      label: 'Amount > $5000?',
      description: 'Check if invoice requires additional approval',
      x: 700,
      y: 300,
      config: {
        condition_type: 'simple',
        condition: 'amount > 5000',
      },
    },
    {
      id: 'auto-approve',
      type: 'skill',
      label: 'Auto Approval',
      description: 'Automatically approve low-value invoices',
      x: 900,
      y: 200,
      config: {
        skill_type: 'api_call',
        endpoint: '/invoices/approve',
        method: 'POST',
      },
    },
    {
      id: 'manual-review',
      type: 'skill',
      label: 'Manual Review Queue',
      description: 'Queue high-value invoices for manager approval',
      x: 900,
      y: 350,
      config: {
        skill_type: 'workflow_trigger',
        parameters: 'approval_workflow, manager_notification',
      },
    },
    {
      id: 'payment-scheduling',
      type: 'skill',
      label: 'Payment Scheduling',
      description: 'Schedule payment based on terms',
      x: 1100,
      y: 275,
      config: {
        skill_type: 'api_call',
        endpoint: '/payments/schedule',
        method: 'POST',
      },
    },
    {
      id: 'processed-invoice',
      type: 'output',
      label: 'Processed Invoice',
      description: 'Invoice approved and scheduled for payment',
      x: 1300,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'invoice-input',
      target: 'ocr-extraction',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'ocr-extraction',
      target: 'data-validator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'data-validator',
      target: 'vendor-lookup',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'data-validator',
      target: 'amount-validation',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'vendor-lookup',
      target: 'auto-approve',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'amount-validation',
      target: 'auto-approve',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'amount-validation',
      target: 'manual-review',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'auto-approve',
      target: 'payment-scheduling',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'manual-review',
      target: 'payment-scheduling',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'payment-scheduling',
      target: 'processed-invoice',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
