import { Template } from '../types';

export const patientTriageTemplate: Template = {
  id: 'patient-triage',
  name: 'AI-Powered Patient Triage',
  description: 'Intelligent patient triage and prioritization for healthcare',
  category: 'healthcare',
  nodes: [
    {
      id: 'patient-input',
      type: 'input',
      label: 'Patient Information',
      description: 'Symptoms, medical history, and vital signs',
      x: 100,
      y: 250,
    },
    {
      id: 'symptom-analyzer',
      type: 'skill',
      label: 'Symptom Analysis',
      description: 'Analyze reported symptoms and severity',
      x: 300,
      y: 200,
      config: {
        skill_type: 'medical_nlp',
        parameters: 'symptom_extraction, severity_assessment, duration_analysis',
      },
    },
    {
      id: 'vital-signs-monitor',
      type: 'sensor',
      label: 'Vital Signs Monitor',
      description: 'Monitor and analyze vital signs data',
      x: 300,
      y: 300,
      config: {
        source_type: 'medical_device',
        parameters: 'heart_rate, blood_pressure, temperature, oxygen_saturation',
      },
    },
    {
      id: 'triage-nurse-ai',
      type: 'agent',
      label: 'Triage Nurse AI',
      description: 'AI assistant trained in medical triage protocols',
      x: 500,
      y: 200,
      config: {
        model: 'medical-llm',
        temperature: 0.1,
        max_tokens: 800,
        system_prompt:
          'Assess patient conditions and recommend appropriate care levels following medical triage protocols.',
      },
    },
    {
      id: 'risk-assessor',
      type: 'skill',
      label: 'Risk Assessment',
      description: 'Calculate patient risk scores and urgency levels',
      x: 500,
      y: 350,
      config: {
        skill_type: 'risk_scoring',
        parameters: 'emergency_score, deterioration_risk, comorbidity_assessment',
      },
    },
    {
      id: 'priority-classifier',
      type: 'decision',
      label: 'Priority Level?',
      description: 'Classify patient priority level for care',
      x: 700,
      y: 275,
      config: {
        condition_type: 'medical_priority',
        condition: 'calculateTriagePriority(symptoms, vitals, risk)',
      },
    },
    {
      id: 'emergency-alert',
      type: 'skill',
      label: 'Emergency Alert',
      description: 'Immediate alert for critical cases',
      x: 900,
      y: 150,
      config: {
        skill_type: 'emergency_notification',
        parameters: 'critical_alert, emergency_team, immediate_response',
      },
    },
    {
      id: 'urgent-queue',
      type: 'skill',
      label: 'Urgent Care Queue',
      description: 'Queue for urgent but non-critical cases',
      x: 900,
      y: 250,
      config: {
        skill_type: 'queue_management',
        parameters: 'urgent_priority, estimated_wait_time, resource_allocation',
      },
    },
    {
      id: 'routine-scheduling',
      type: 'skill',
      label: 'Routine Scheduling',
      description: 'Schedule routine appointments',
      x: 900,
      y: 350,
      config: {
        skill_type: 'appointment_scheduling',
        parameters: 'standard_appointment, availability_check, provider_match',
      },
    },
    {
      id: 'care-coordinator',
      type: 'agent',
      label: 'Care Coordinator',
      description: 'Coordinate appropriate care pathway',
      x: 1100,
      y: 200,
      config: {
        model: 'healthcare-gpt',
        temperature: 0.2,
        max_tokens: 600,
        system_prompt:
          'Coordinate patient care pathways and ensure appropriate resource allocation.',
      },
    },
    {
      id: 'patient-communication',
      type: 'skill',
      label: 'Patient Communication',
      description: 'Communicate triage results and next steps to patient',
      x: 1100,
      y: 350,
      config: {
        skill_type: 'patient_communication',
        parameters: 'wait_time_notification, care_instructions, appointment_confirmation',
      },
    },
    {
      id: 'triaged-patient',
      type: 'output',
      label: 'Triaged Patient',
      description: 'Patient appropriately triaged and routed for care',
      x: 1300,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'patient-input',
      target: 'symptom-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'patient-input',
      target: 'vital-signs-monitor',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'symptom-analyzer',
      target: 'triage-nurse-ai',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'vital-signs-monitor',
      target: 'risk-assessor',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'triage-nurse-ai',
      target: 'priority-classifier',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'risk-assessor',
      target: 'priority-classifier',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'priority-classifier',
      target: 'emergency-alert',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'priority-classifier',
      target: 'urgent-queue',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'priority-classifier',
      target: 'routine-scheduling',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'emergency-alert',
      target: 'care-coordinator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'urgent-queue',
      target: 'care-coordinator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'routine-scheduling',
      target: 'patient-communication',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'care-coordinator',
      target: 'triaged-patient',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'patient-communication',
      target: 'triaged-patient',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
