import { Template } from '../types';

export const productRecommendationTemplate: Template = {
  id: 'product-recommendation',
  name: 'AI Product Recommendation Engine',
  description: 'Personalized product recommendations for e-commerce',
  category: 'e-commerce',
  nodes: [
    {
      id: 'customer-data',
      type: 'input',
      label: 'Customer Data',
      description: 'User profile, browsing history, and purchase data',
      x: 100,
      y: 250,
    },
    {
      id: 'behavior-analyzer',
      type: 'skill',
      label: 'Behavior Analysis',
      description: 'Analyze customer browsing and purchase patterns',
      x: 300,
      y: 200,
      config: {
        skill_type: 'behavioral_analysis',
        parameters: 'click_stream, session_duration, cart_abandonment, purchase_frequency',
      },
    },
    {
      id: 'preference-extractor',
      type: 'skill',
      label: 'Preference Extraction',
      description: 'Extract customer preferences from interaction data',
      x: 300,
      y: 300,
      config: {
        skill_type: 'preference_mining',
        parameters: 'category_preferences, brand_affinity, price_sensitivity, style_preferences',
      },
    },
    {
      id: 'recommendation-ai',
      type: 'agent',
      label: 'Recommendation AI',
      description: 'AI agent specialized in product recommendation logic',
      x: 500,
      y: 200,
      config: {
        model: 'recommendation-llm',
        temperature: 0.3,
        max_tokens: 800,
        system_prompt:
          'Generate personalized product recommendations based on customer behavior and preferences.',
      },
    },
    {
      id: 'collaborative-filter',
      type: 'skill',
      label: 'Collaborative Filtering',
      description: 'Find similar customers and their preferences',
      x: 500,
      y: 350,
      config: {
        skill_type: 'collaborative_filtering',
        parameters: 'user_similarity, item_similarity, matrix_factorization',
      },
    },
    {
      id: 'content-filter',
      type: 'skill',
      label: 'Content-Based Filtering',
      description: 'Recommend based on product features and attributes',
      x: 700,
      y: 150,
      config: {
        skill_type: 'content_filtering',
        parameters: 'product_attributes, feature_matching, category_correlation',
      },
    },
    {
      id: 'inventory-checker',
      type: 'skill',
      label: 'Inventory Availability',
      description: 'Check product availability and stock levels',
      x: 700,
      y: 250,
      config: {
        skill_type: 'inventory_lookup',
        parameters: 'stock_levels, availability_status, delivery_timeframes',
      },
    },
    {
      id: 'trend-analyzer',
      type: 'skill',
      label: 'Trend Analysis',
      description: 'Factor in current trends and seasonal patterns',
      x: 700,
      y: 350,
      config: {
        skill_type: 'trend_analysis',
        parameters: 'seasonal_trends, popular_items, emerging_categories',
      },
    },
    {
      id: 'recommendation-ranker',
      type: 'skill',
      label: 'Recommendation Ranking',
      description: 'Rank and score recommendations by relevance',
      x: 900,
      y: 250,
      config: {
        skill_type: 'ranking_algorithm',
        parameters: 'relevance_score, popularity_boost, diversity_factor, novelty_score',
      },
    },
    {
      id: 'personalization-engine',
      type: 'agent',
      label: 'Personalization Engine',
      description: 'Fine-tune recommendations for individual customers',
      x: 1100,
      y: 200,
      config: {
        model: 'personalization-gpt',
        temperature: 0.4,
        max_tokens: 600,
        system_prompt:
          'Personalize product recommendations based on individual customer context and preferences.',
      },
    },
    {
      id: 'ab-test-optimizer',
      type: 'skill',
      label: 'A/B Test Optimizer',
      description: 'Optimize recommendations based on A/B test results',
      x: 1100,
      y: 300,
      config: {
        skill_type: 'ab_testing',
        parameters: 'conversion_tracking, click_through_rates, revenue_optimization',
      },
    },
    {
      id: 'recommendation-formatter',
      type: 'skill',
      label: 'Recommendation Formatter',
      description: 'Format recommendations for different display contexts',
      x: 1300,
      y: 200,
      config: {
        skill_type: 'content_formatting',
        parameters: 'homepage_carousel, email_recommendations, product_page_suggestions',
      },
    },
    {
      id: 'performance-tracker',
      type: 'skill',
      label: 'Performance Tracking',
      description: 'Track recommendation performance and user engagement',
      x: 1300,
      y: 350,
      config: {
        skill_type: 'analytics',
        parameters: 'ctr_tracking, conversion_rates, revenue_attribution, user_feedback',
      },
    },
    {
      id: 'personalized-recommendations',
      type: 'output',
      label: 'Personalized Recommendations',
      description: 'Tailored product recommendations for the customer',
      x: 1500,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'customer-data',
      target: 'behavior-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'customer-data',
      target: 'preference-extractor',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'behavior-analyzer',
      target: 'recommendation-ai',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'preference-extractor',
      target: 'collaborative-filter',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recommendation-ai',
      target: 'content-filter',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recommendation-ai',
      target: 'inventory-checker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'collaborative-filter',
      target: 'trend-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-filter',
      target: 'recommendation-ranker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'inventory-checker',
      target: 'recommendation-ranker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'trend-analyzer',
      target: 'recommendation-ranker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recommendation-ranker',
      target: 'personalization-engine',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recommendation-ranker',
      target: 'ab-test-optimizer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'personalization-engine',
      target: 'recommendation-formatter',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'ab-test-optimizer',
      target: 'performance-tracker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'recommendation-formatter',
      target: 'personalized-recommendations',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'performance-tracker',
      target: 'personalized-recommendations',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
