import { Template } from '../types';

export const socialMediaContentTemplate: Template = {
  id: 'social-media-content',
  name: 'Social Media Content Pipeline',
  description: 'Automated social media content creation and scheduling',
  category: 'content-creation',
  nodes: [
    {
      id: 'content-brief',
      type: 'input',
      label: 'Content Brief',
      description: 'Campaign goals, target audience, and key messages',
      x: 100,
      y: 250,
    },
    {
      id: 'trend-analyzer',
      type: 'skill',
      label: 'Trend Analysis',
      description: 'Analyze current social media trends and hashtags',
      x: 300,
      y: 150,
      config: {
        skill_type: 'social_listening',
        parameters: 'trending_topics, hashtag_analysis, competitor_content',
      },
    },
    {
      id: 'audience-profiler',
      type: 'skill',
      label: 'Audience Profiling',
      description: 'Analyze target audience preferences and behavior',
      x: 300,
      y: 250,
      config: {
        skill_type: 'audience_analysis',
        parameters: 'demographics, interests, engagement_patterns',
      },
    },
    {
      id: 'content-ideation',
      type: 'agent',
      label: 'Content Ideation Agent',
      description: 'Generate creative content ideas based on trends and audience',
      x: 500,
      y: 200,
      config: {
        model: 'gpt-4',
        temperature: 0.7,
        max_tokens: 600,
        system_prompt:
          'Generate creative, engaging social media content ideas that align with brand voice and current trends.',
      },
    },
    {
      id: 'copywriter-agent',
      type: 'agent',
      label: 'AI Copywriter',
      description: 'Write engaging social media copy for different platforms',
      x: 700,
      y: 150,
      config: {
        model: 'claude-3',
        temperature: 0.6,
        max_tokens: 500,
        system_prompt:
          'Write compelling social media copy optimized for each platform. Be engaging, authentic, and on-brand.',
      },
    },
    {
      id: 'image-generator',
      type: 'skill',
      label: 'Visual Content Creator',
      description: 'Generate images and graphics for posts',
      x: 700,
      y: 250,
      config: {
        skill_type: 'image_generation',
        parameters: 'dall-e, midjourney, canva_integration',
      },
    },
    {
      id: 'hashtag-optimizer',
      type: 'skill',
      label: 'Hashtag Optimizer',
      description: 'Suggest optimal hashtags for maximum reach',
      x: 700,
      y: 350,
      config: {
        skill_type: 'hashtag_research',
        parameters: 'trending_hashtags, niche_tags, reach_optimization',
      },
    },
    {
      id: 'platform-adapter',
      type: 'skill',
      label: 'Platform Optimization',
      description: 'Adapt content for each social media platform',
      x: 900,
      y: 200,
      config: {
        skill_type: 'content_adaptation',
        parameters: 'instagram, twitter, facebook, linkedin, tiktok',
      },
    },
    {
      id: 'approval-workflow',
      type: 'decision',
      label: 'Content Approved?',
      description: 'Review and approval process',
      x: 900,
      y: 350,
      config: {
        condition_type: 'manual_approval',
        condition: 'content_review_required',
      },
    },
    {
      id: 'scheduler',
      type: 'skill',
      label: 'Post Scheduler',
      description: 'Schedule posts for optimal engagement times',
      x: 1100,
      y: 200,
      config: {
        skill_type: 'social_scheduling',
        parameters: 'optimal_timing, platform_scheduling, buffer_integration',
      },
    },
    {
      id: 'performance-tracker',
      type: 'skill',
      label: 'Performance Tracking',
      description: 'Monitor post performance and engagement metrics',
      x: 1100,
      y: 350,
      config: {
        skill_type: 'analytics',
        parameters: 'engagement_tracking, reach_analysis, roi_measurement',
      },
    },
    {
      id: 'published-content',
      type: 'output',
      label: 'Published Social Content',
      description: 'Content published across all social platforms',
      x: 1300,
      y: 275,
    },
  ],
  connections: [
    {
      source: 'content-brief',
      target: 'trend-analyzer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-brief',
      target: 'audience-profiler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'trend-analyzer',
      target: 'content-ideation',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'audience-profiler',
      target: 'content-ideation',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-ideation',
      target: 'copywriter-agent',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-ideation',
      target: 'image-generator',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'content-ideation',
      target: 'hashtag-optimizer',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'copywriter-agent',
      target: 'platform-adapter',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'image-generator',
      target: 'platform-adapter',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'hashtag-optimizer',
      target: 'approval-workflow',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'platform-adapter',
      target: 'approval-workflow',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'approval-workflow',
      target: 'scheduler',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'approval-workflow',
      target: 'performance-tracker',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'scheduler',
      target: 'published-content',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
    {
      source: 'performance-tracker',
      target: 'published-content',
      sourceHandle: 'right',
      targetHandle: 'left',
    },
  ],
};
