name: Nightly E2E Tests

on:
  schedule:
    # Run at 2 AM UTC every night
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering
    inputs:
      test_pattern:
        description: "Test pattern to run (optional)"
        required: false
        default: ""

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false # Continue with other browsers even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "27"

      - name: Install Elixir dependencies
        run: mix deps.get

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"

      - name: Setup test database
        run: |
          mix ecto.create
          mix ecto.migrate
        env:
          MIX_ENV: e2e
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres

      - name: Compile application
        run: mix compile
        env:
          MIX_ENV: e2e

      - name: Build assets
        run: mix assets.build
        env:
          MIX_ENV: e2e

      - name: Start Phoenix server in background
        run: |
          mix phx.server &
          echo $! > phoenix.pid
          # Wait for server to be ready
          timeout 30 bash -c 'until curl -f http://localhost:4000/; do sleep 1; done'
        env:
          MIX_ENV: e2e
          PORT: 4000

      - name: Run E2E tests
        run: |
          if [ -n "${{ github.event.inputs.test_pattern }}" ]; then
            npx playwright test --project=${{ matrix.browser }} --grep="${{ github.event.inputs.test_pattern }}"
          else
            npx playwright test --project=${{ matrix.browser }}
          fi
        env:
          CI: true

      - name: Stop Phoenix server
        if: always()
        run: |
          if [ -f phoenix.pid ]; then
            kill $(cat phoenix.pid) || true
            rm phoenix.pid
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-${{ matrix.browser }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7

      - name: Upload test videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-videos-${{ matrix.browser }}
          path: test-results/**/video.webm
          retention-days: 3

  notify-results:
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create test summary
        run: |
          echo "# Nightly E2E Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.e2e-tests.result }}" == "success" ]]; then
            echo "✅ **Status:** All E2E tests passed across all browsers!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Status:** Some E2E tests failed. Check the individual job results for details." >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Browser Results" >> $GITHUB_STEP_SUMMARY
          echo "Check the individual job results in the workflow run for detailed browser-specific results." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tested Browsers:** Chromium, Firefox, WebKit" >> $GITHUB_STEP_SUMMARY

      # Optional: Send notification to Slack/Discord/email if tests fail
      # - name: Notify on failure
      #   if: needs.e2e-tests.result == 'failure'
      #   run: |
      #     echo "E2E tests failed. Consider sending notification here."
