name: Open Source Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Mondays at 6 AM UTC

jobs:
  codecov:
    name: Codecov Coverage
    runs-on: ubuntu-latest
    
    env:
      MIX_ENV: test

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: helix_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "27"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-25-1.14-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        run: |
          mix deps.get
          npm ci

      - name: Build assets
        run: mix assets.build

      - name: Run Elixir tests with coverage
        run: mix test --cover

      - name: Generate coverage reports
        run: |
          mix coveralls.json
          npm run test:coverage || echo "No frontend tests yet"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./cover/excoveralls.json,./coverage/lcov.info
          flags: unittests
          name: helix-coverage

